#!/bin/sh
export FLASK_APP=/home/fsantiag/flask-app/iphone8.py
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
case "$1" in
  start)
	echo 'Starting Iphone 8 web application...'
	nohup python3 -m flask run --host=0.0.0.0 --port=54321 > /home/fsantiag/log.txt 2>&1 &
	;;
  stop)
	echo 'Stopping Iphone 8 web application...'
	killall flask
	;;
esac

exit 0
