---
- hosts: aws
  user: fsantiag
  become: true
  vars:
    app_name: flask-app
    repo_url: https://user:password@github.com/jfelipefilho/flask-app.git
    home: /home/fsantiag

  tasks:
    - name: Install git, python and pip
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python3
        - python3-pip

    - name: Clone app
      git: repo={{repo_url}} dest={{home}}/{{app_name}}

    - name: Install app requirements
      pip: executable=pip3 requirements={{home}}/{{app_name}}/requirements.txt

    - name: Copy service iphone8 init script
      copy: src={{home}}/{{app_name}}/fsantiag.service dest=/etc/systemd/system remote_src=true owner=root group=root

    - name: Start iphone8 flask service
      systemd:
        name: fsantiag.service
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Reboot
      command: reboot
      poll: 0
